name: Update Readme

on:
  schedule:
    # 9:30 - 9:55 (每五分钟一次)
    - cron: "30 9 * * *" # 9:30
    - cron: "35 9 * * *" # 9:35
    - cron: "40 9 * * *" # 9:40
    - cron: "45 9 * * *" # 9:45
    - cron: "50 9 * * *" # 9:50
    - cron: "55 9 * * *" # 9:55

    # 10:00 - 10:55 (每五分钟一次)
    - cron: "0 2 * * *" # 10:00
    - cron: "5 2 * * *" # 10:05
    - cron: "10 2 * * *" # 10:10
    - cron: "15 2 * * *" # 10:15
    - cron: "20 2 * * *" # 10:20
    - cron: "25 2 * * *" # 10:25
    - cron: "30 2 * * *" # 10:30
    - cron: "35 2 * * *" # 10:35
    - cron: "40 2 * * *" # 10:40
    - cron: "45 2 * * *" # 10:45
    - cron: "50 2 * * *" # 10:50
    - cron: "55 2 * * *" # 10:55

    # 11:00 - 11:30 (每五分钟一次)
    - cron: "0 3 * * *" # 11:00
    - cron: "5 3 * * *" # 11:05
    - cron: "10 3 * * *" # 11:10
    - cron: "15 3 * * *" # 11:15
    - cron: "20 3 * * *" # 11:20
    - cron: "25 3 * * *" # 11:25
    - cron: "30 3 * * *" # 11:30

    # 13:00 - 13:55 (每五分钟一次)
    - cron: "0 5 * * *" # 13:00
    - cron: "5 5 * * *" # 13:05
    - cron: "10 5 * * *" # 13:10
    - cron: "15 5 * * *" # 13:15
    - cron: "20 5 * * *" # 13:20
    - cron: "25 5 * * *" # 13:25
    - cron: "30 5 * * *" # 13:30
    - cron: "35 5 * * *" # 13:35
    - cron: "40 5 * * *" # 13:40
    - cron: "45 5 * * *" # 13:45
    - cron: "50 5 * * *" # 13:50
    - cron: "55 5 * * *" # 13:55

    # 14:00 - 14:55 (每五分钟一次)
    - cron: "0 6 * * *" # 14:00
    - cron: "5 6 * * *" # 14:05
    - cron: "10 6 * * *" # 14:10
    - cron: "15 6 * * *" # 14:15
    - cron: "20 6 * * *" # 14:20
    - cron: "25 6 * * *" # 14:25
    - cron: "30 6 * * *" # 14:30
    - cron: "35 6 * * *" # 14:35
    - cron: "40 6 * * *" # 14:40
    - cron: "45 6 * * *" # 14:45
    - cron: "50 6 * * *" # 14:50
    - cron: "55 6 * * *" # 14:55

    # 15:00 - (每五分钟一次)
    - cron: "0 7 * * *" # 15:00

env:
  TZ: Asia/Shanghai

jobs:
  # a single job
  a-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install akshare
          pip3 install mplfinance

      - name: Run
        run: python3 ./main.py

      - name: Commit
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: |
          git config --local user.name $USER_NAME
          git config --local user.email $USER_EMAIL
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.USER_TOKEN }}
          branch: main
