name: Update Readme

on:
  push:
  schedule:
    # 9:30 - 9:55 (每五分钟一次)
    - cron: "30 9 * * *" # 9:30
    - cron: "35 9 * * *" # 9:35
    - cron: "40 9 * * *" # 9:40
    - cron: "45 9 * * *" # 9:45
    - cron: "50 9 * * *" # 9:50
    - cron: "55 9 * * *" # 9:55

    # 10:00 - 10:55 (每五分钟一次)
    - cron: "0 10 * * *" # 10:00
    - cron: "5 10 * * *" # 10:05
    - cron: "10 10 * * *" # 10:10
    - cron: "15 10 * * *" # 10:15
    - cron: "20 10 * * *" # 10:20
    - cron: "25 10 * * *" # 10:25
    - cron: "30 10 * * *" # 10:30
    - cron: "35 10 * * *" # 10:35
    - cron: "40 10 * * *" # 10:40
    - cron: "45 10 * * *" # 10:45
    - cron: "50 10 * * *" # 10:50
    - cron: "55 10 * * *" # 10:55

    # 11:00 - 11:30 (每五分钟一次)
    - cron: "0 11 * * *" # 11:00
    - cron: "5 11 * * *" # 11:05
    - cron: "10 11 * * *" # 11:10
    - cron: "15 11 * * *" # 11:15
    - cron: "20 11 * * *" # 11:20
    - cron: "25 11 * * *" # 11:25
    - cron: "30 11 * * *" # 11:30

    # 13:00 - 13:55 (每五分钟一次)
    - cron: "0 13 * * *" # 13:00
    - cron: "5 13 * * *" # 13:05
    - cron: "10 13 * * *" # 13:10
    - cron: "15 13 * * *" # 13:15
    - cron: "20 13 * * *" # 13:20
    - cron: "25 13 * * *" # 13:25
    - cron: "30 13 * * *" # 13:30
    - cron: "35 13 * * *" # 13:35
    - cron: "40 13 * * *" # 13:40
    - cron: "45 13 * * *" # 13:45
    - cron: "50 13 * * *" # 13:50
    - cron: "55 13 * * *" # 13:55

    # 14:00 - 14:55 (每五分钟一次)
    - cron: "0 14 * * *" # 14:00
    - cron: "5 14 * * *" # 14:05
    - cron: "10 14 * * *" # 14:10
    - cron: "15 14 * * *" # 14:15
    - cron: "20 14 * * *" # 14:20
    - cron: "25 14 * * *" # 14:25
    - cron: "30 14 * * *" # 14:30
    - cron: "35 14 * * *" # 14:35
    - cron: "40 14 * * *" # 14:40
    - cron: "45 14 * * *" # 14:45
    - cron: "50 14 * * *" # 14:50
    - cron: "55 14 * * *" # 14:55

    # 15:00 - (每五分钟一次)
    - cron: "0 15 * * *" # 15:00

env:
  TZ: Asia/Shanghai

jobs:
  # a single job
  a-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install akshare
          pip3 install mplfinance

      - name: Run
        run: python3 ./main.py

      - name: Commit
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: |
          git config --local user.name $USER_NAME
          git config --local user.email $USER_EMAIL
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.USER_TOKEN }}
          branch: main
